server:
  port: 8091

spring:
  datasource:
    url: jdbc:mysql://49.232.32.126:3306/pig
    username: root
    password: QfaZpdNp2DZZUtja79JS
    spring.datasource.driver-class-name: com.mysql.jdbc.Driver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5

logging:
  level:
    com.example.demo.dao : debug

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
